Dz4 card
js-tasks-ru/htmlcss-20211021_tina-tezadova pull request #12
Opened 2021-11-08 06:55 UTC by TinaTezadova

2021-11-08 06:56 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-08 06:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-10 20:07 UTC, GSemikozov requested changes

2021-11-10 20:07 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__amount_preview {
достаточно одного общего модификатора блока, и уже через него менять значения дочерним элементам

2021-11-11 07:17 UTC, TinaTezadova commented on 04-lection2/01-histogram/histogram.css
> +.histogram__amount_preview {
Я через модификатор блока указала общие свойства, но свойство font-weight: 600 требуется только для одного элемента. Как быть в таком случае?

2021-11-11 14:37 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__amount_preview {
наверно так: .histogram_preview .histogram__your_specific_element

2021-11-11 15:13 UTC, TinaTezadova commented on 04-lection2/01-histogram/histogram.css
> +.histogram__amount_preview {
готово

2021-11-11 15:22 UTC, GSemikozov approved these changes

2021-11-11 15:22 UTC, merged