Dz7 tabs
js-tasks-ru/htmlcss-20211021_tina-tezadova pull request #23
Opened 2021-11-18 07:15 UTC by TinaTezadova

2021-11-18 07:16 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-18 11:38 UTC, GSemikozov requested changes

2021-11-18 11:38 UTC, GSemikozov commented on components/tabs/tabs.css
> +ul {
глобальные сбросы - в normalize.css?

2021-11-18 11:38 UTC, GSemikozov commented on components/tabs/tabs.css
> +.tabs__menu > li {
селекторы тегов е используем, можно избежать и вложенных селекторов, просто задав класс элементу списка, например .tabs__menu-item

2021-11-18 11:38 UTC, GSemikozov commented on index.html
> +    <main>
сверху меню табов есть, это хорошо. Но - через меню мы должны переключать блоки с разным контентом вот здесь ниже, а это не реализовано)

2021-11-18 15:06 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-18 15:13 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-18 15:22 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-19 06:50 UTC, TinaTezadova commented on components/tabs/tabs.css
> +ul {
Поправила

2021-11-19 06:50 UTC, TinaTezadova commented on components/tabs/tabs.css
> +.tabs__menu > li {
Поправила

2021-11-19 06:50 UTC, TinaTezadova commented on index.html
> +    <main>
Поправила

2021-11-19 06:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-19 09:42 UTC, GSemikozov requested changes

2021-11-19 09:42 UTC, GSemikozov commented on components/tabs/tabs.css
> + .tab__state {
.tab__state ->  .tabs__state

2021-11-19 09:42 UTC, GSemikozov commented on components/tabs/tabs.css
> + .tab__state {
или  .tabs__tab-state

2021-11-19 09:42 UTC, GSemikozov commented on components/tabs/tabs.css
> +.tab__label {
.tab__label -> .tabs__tab-label

2021-11-19 09:42 UTC, GSemikozov commented on components/tabs/tabs.css
> +.tab__label::after {
.tabs__tab-label

2021-11-19 09:42 UTC, GSemikozov commented on components/tabs/tabs.css
> +.tab__label-container {
.tabs__tab-label-container

2021-11-19 09:42 UTC, GSemikozov commented on components/tabs/tabs.css
> +.tab_all:checked ~ .tabs__content_complex {
.tabs__tab_all
и ниже по аналогии

2021-11-19 09:42 UTC, GSemikozov commented on components/tabs/tabs.css
> +.tab_all:checked ~ .tabs__nav > .container > .tab__state > .tabs__menu > .tabs__menu-item > .tab__label-container >  #all-tab-label::after {
это перебор)) не нужно перечислять каждый уровень вложенности.
достаточно указать .tabs__tab_all:checked ~  .tabs__nav #all-tab-label
и ниже по аналогии

2021-11-19 09:52 UTC, TinaTezadova commented on components/tabs/tabs.css
> + .tab__state {
Поправила

2021-11-19 09:52 UTC, TinaTezadova commented on components/tabs/tabs.css
> +.tab__label {
Поправила

2021-11-19 09:52 UTC, TinaTezadova commented on components/tabs/tabs.css
> +.tab__label::after {
Поправила

2021-11-19 09:52 UTC, TinaTezadova commented on components/tabs/tabs.css
> +.tab__label-container {
Готово

2021-11-19 09:52 UTC, TinaTezadova commented on components/tabs/tabs.css
> +.tab_all:checked ~ .tabs__content_complex {
Готово

2021-11-19 09:52 UTC, TinaTezadova commented on components/tabs/tabs.css
> +.tab_all:checked ~ .tabs__nav > .container > .tab__state > .tabs__menu > .tabs__menu-item > .tab__label-container >  #all-tab-label::after {
Поправила, спасибо

2021-11-19 09:53 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-19 09:56 UTC, GSemikozov approved these changes

2021-11-19 09:56 UTC, merged