Тултип
js-tasks-ru/htmlcss-20211021_tina-tezadova pull request #9
Opened 2021-11-02 10:43 UTC by TinaTezadova

2021-11-02 10:44 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-03 12:31 UTC, GSemikozov requested changes

2021-11-03 12:31 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    transform: translate(-50%, -85px);
если изменится высота триггера - тултип будет наползать или наоборот отдаляться от него, а чтобы это не происходило, лучше указать еще top: 100% или bottom: 0 + в transform уже не -85 а более мелкое число)

2021-11-03 12:31 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +body {
общие стили никогда не описываем в файлах компонентов (если у каждого компонента будет свой body padding-top то в итоге 100% получим конфликт стилей и не то что нам надо). Если это стили чисто вспомогательные, их можно размещать в style страницы с решением

2021-11-03 13:26 UTC, TinaTezadova commented on 05-lection3/01-tooltip/tooltip.css
> +    transform: translate(-50%, -85px);
готово

2021-11-03 13:26 UTC, TinaTezadova commented on 05-lection3/01-tooltip/tooltip.css
> +body {
готово

2021-11-03 19:44 UTC, GSemikozov approved these changes

2021-11-03 19:45 UTC, merged